# Generated by Django 5.2.7 on 2025-10-30 18:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='max_score',
            field=models.IntegerField(default=0, help_text='Maximum possible marks for this attempt'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_option_index',
            field=models.IntegerField(default=0, help_text='Selected option index (0-3) - deprecated', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='total_marks',
            field=models.IntegerField(default=0, help_text='Total marks for this attempt (deprecated, use max_score)'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, help_text='Selected option (new approach)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.option'),
        ),
    ]
